"""
Report Agent - Generates final literature review reports.
"""

from collections import Counter
from typing import List, Optional
from datetime import datetime

from ..storage.models.agent_models import (
    LiteratureReviewReport, ReportMetadata, AnalysisResult,
    AuthorAnalysis, AuthorProfile, AuthorPublication, PaperSummary,
)

_MAX_KEY_PUBLICATIONS_PER_AUTHOR = 5
_MAX_SPECIALIZATIONS_PER_AUTHOR = 5


def _keywords(text: str, limit: int) -> list[str]:
    """Most frequent content words in `text`, original (non-stemmed) form,
    most common first. Same NLTK stopword/tokenize approach as
    `utils.text.significant_words`, but keeping the real word instead of a
    Porter stem -- these are shown directly to a human in the research
    directory, and a stem like "quantiz" reads worse than "quantization"."""
    try:
        from nltk.tokenize import word_tokenize
        from nltk.corpus import stopwords as _sw
        tokens = word_tokenize(text.lower())
        stop = set(_sw.words("english"))
    except LookupError:
        import nltk as _nltk
        _nltk.download("punkt_tab", quiet=True)
        _nltk.download("stopwords", quiet=True)
        from nltk.tokenize import word_tokenize
        from nltk.corpus import stopwords as _sw
        tokens = word_tokenize(text.lower())
        stop = set(_sw.words("english"))

    words = [t for t in tokens if t.isalpha() and t not in stop and len(t) > 2]
    return [word for word, _count in Counter(words).most_common(limit)]


class ReportAgent:
    """Generate structured literature review reports."""
    
    def __init__(self):
        self.output_formats = ['markdown', 'json', 'csv']
    
    def generate(self, analysis_result: AnalysisResult, config: dict) -> LiteratureReviewReport:
        """
        Generate final literature review report.
        
        Args:
            analysis_result: AnalysisResult from AnalysisAgent
            config: Report configuration (format, sections, etc.)
            
        Returns:
            LiteratureReviewReport with structured content
        """
        # Generate report metadata
        metadata = ReportMetadata(
            search_query=config.get('topic', 'Unknown'),
            sources_used=config.get('sources', []),
            papers_analyzed=analysis_result.total_papers,
            total_processing_time=config.get('total_time'),
            search_time=config.get('search_time'),
            analysis_time=config.get('analysis_time'),
            report_time=0.0  # Will be calculated
        )
        
        # Generate main content
        content = self._generate_content(analysis_result, config)

        # Optional author analysis / research directory (docs/wiki/features.md's
        # "Optional author analysis" report section) -- off by default, since
        # not every review wants a per-author breakdown appended.
        if config.get('include_authors'):
            author_analysis = self.analyze_authors(analysis_result.summaries)
            content += "\n" + self.create_research_directory(author_analysis)

        # Generate bibliography
        bibliography = self._generate_bibliography(analysis_result.summaries)
        
        # Create the report
        report = LiteratureReviewReport(
            title=f"Literature Review: {config.get('topic', 'Unknown')}",
            summary_count=len(analysis_result.summaries),
            content=content,
            bibliography=bibliography,
            metadata=metadata,
            export_formats=['markdown', 'json']
        )
        
        return report
    
    def _generate_content(self, analysis_result: AnalysisResult, config: dict) -> str:
        """Generate main report content in markdown format."""
        topic = config.get('topic', 'Unknown Topic')
        
        content = f"""# Literature Review: {topic}

Generated by Prisma - Automated Literature Review Tool

## Executive Summary

This review analyzed **{analysis_result.total_papers} papers** on the topic of "{topic}". The analysis identified **{analysis_result.author_count} unique authors** contributing to this research area.

## Methodology

- **Search Query**: {topic}  
- **Sources**: {', '.join(config.get('sources', ['Unknown']))}
- **Papers Analyzed**: {analysis_result.total_papers}
- **Analysis Date**: {analysis_result.analysis_timestamp.strftime('%Y-%m-%d %H:%M:%S')}
- **Average Processing Time**: {analysis_result.avg_processing_time:.2f}s per paper

## Papers Analyzed

"""
        
        for i, summary in enumerate(analysis_result.summaries, 1):
            connected_papers = summary.connected_papers_url or f"https://www.connectedpapers.com/search?q={summary.title.replace(' ', '%20')}"
            
            content += f"""### {i}. {summary.title}

**Authors:** {', '.join(summary.authors) if summary.authors else 'Unknown Authors'}

**Summary:** {summary.summary}

**Key Findings:**
"""
            
            for finding in summary.key_findings:
                content += f"- {finding}\n"
            
            if summary.methodology:
                content += f"\n**Methodology:** {summary.methodology}\n"
            
            content += f"\n**Connected Papers:** [{summary.title}]({connected_papers})\n"
            content += f"**Analysis Confidence:** {summary.analysis_confidence:.1%}\n\n---\n\n"
        
        # Add research insights
        if analysis_result.top_authors:
            content += "\n## Top Contributing Authors\n\n"
            for author in analysis_result.top_authors[:5]:
                content += f"- {author}\n"
        
        content += f"""

## Analysis Summary

- **Total Papers:** {analysis_result.total_papers}
- **Unique Authors:** {analysis_result.author_count}
- **Search Topic:** {topic}
- **Generated:** {config.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}
- **Average Processing Time:** {analysis_result.avg_processing_time:.2f}s per paper

*This is an automated literature review generated by Prisma. Future versions will include advanced analysis, author networks, and thematic grouping.*
"""
        
        return content
    
    def _generate_bibliography(self, summaries: List) -> Optional[List[str]]:
        """Generate bibliography from paper summaries.""" 
        bibliography = []
        for summary in summaries:
            # Generate basic citation format
            authors_str = ', '.join(summary.authors[:3]) if summary.authors else "Unknown Authors"
            if len(summary.authors) > 3:
                authors_str += " et al."
            
            citation = f"{authors_str}. {summary.title}. {summary.url}"
            bibliography.append(citation)
        
        return bibliography if bibliography else None
    
    def _generate_metadata(self, summaries: list, config: dict) -> dict:
        """Generate report metadata."""
        # TODO: Include search parameters, date ranges, source counts
        # TODO: Future: Include ConnectedPapers integration links
        pass
    
    def analyze_authors(self, summaries: List[PaperSummary]) -> AuthorAnalysis:
        """Build a per-author profile for every author appearing in this
        corpus of paper summaries: paper count, specialization keywords
        (frequent words across their titles/key findings), and key
        publications (highest analysis_confidence first, capped).

        No institutional affiliation, research trajectory, or collaboration
        mapping -- see AuthorProfile's docstring for why affiliation is
        left out; trajectory/collaboration are map_collaboration_networks's
        job (unbuilt, a separate increment per docs/wiki/roadmap.md)."""
        by_author: dict[str, list[PaperSummary]] = {}
        for paper in summaries:
            for author in paper.authors:
                by_author.setdefault(author, []).append(paper)

        profiles = []
        for name, papers in by_author.items():
            corpus_text = " ".join(
                p.title + " " + " ".join(p.key_findings) for p in papers
            )
            ranked_papers = sorted(
                papers, key=lambda p: p.analysis_confidence or 0.0, reverse=True,
            )
            profiles.append(AuthorProfile(
                name=name,
                paper_count=len(papers),
                specializations=_keywords(corpus_text, _MAX_SPECIALIZATIONS_PER_AUTHOR),
                key_publications=[
                    AuthorPublication(title=p.title, url=p.url)
                    for p in ranked_papers[:_MAX_KEY_PUBLICATIONS_PER_AUTHOR]
                ],
            ))
        profiles.sort(key=lambda p: p.paper_count, reverse=True)
        return AuthorAnalysis(authors=profiles, total_unique_authors=len(profiles))

    def create_research_directory(self, author_analysis: AuthorAnalysis) -> str:
        """Render `analyze_authors()`'s result as a Markdown directory --
        one section per author, most prolific (in this corpus) first."""
        lines = [
            "## Research Directory",
            "",
            f"{author_analysis.total_unique_authors} unique author"
            f"{'s' if author_analysis.total_unique_authors != 1 else ''} "
            "in this corpus.",
            "",
            "*Institutional affiliation isn't shown -- no search source Prisma "
            "indexes captures it, and guessing from an abstract risks "
            "fabricating a detail that matters for an academic tool.*",
            "",
        ]
        for profile in author_analysis.authors:
            lines.append(f"### {profile.name}")
            lines.append(f"**Papers in this corpus:** {profile.paper_count}")
            if profile.specializations:
                lines.append(f"**Specializations:** {', '.join(profile.specializations)}")
            if profile.key_publications:
                lines.append("**Key publications:**")
                for pub in profile.key_publications:
                    lines.append(f"- [{pub.title}]({pub.url})")
            lines.append("")
        return "\n".join(lines)
    
    def map_collaboration_networks(self, summaries: list) -> dict:
        """
        Map research collaboration networks and partnerships.
        
        Args:
            summaries: List of paper summaries with co-authorship data
            
        Returns:
            Network analysis of research collaborations
        """
        # TODO: Analyze co-authorship patterns
        # TODO: Identify research clusters and communities  
        # TODO: Track advisor-student relationships
        # TODO: Map inter-institutional collaborations
        pass
    
    def generate_connected_papers_links(self, summaries: list) -> list:
        """
        Generate ConnectedPapers.com URLs for citation network visualization.
        
        Args:
            summaries: List of paper summaries with DOI/arXiv identifiers
            
        Returns:
            List of ConnectedPapers URLs for key papers
        """
        # TODO: Extract DOI/arXiv IDs from papers
        # TODO: Generate ConnectedPapers URLs
        # Example: https://www.connectedpapers.com/main/{paper_id}/graph
        # TODO: Include in final report for network exploration
        pass
    
    def save_report(self, report: dict, filepath: str) -> bool:
        """Save report to file system."""
        # TODO: Implement file saving in multiple formats
        pass